const translateText = [
    ['.top_section .subtitle', '学びのオリンピック', '<span>Shibuya Olympiad </span><span>in Liberal Arts</span>'],
    ['.event_section .section_title', 'イベント情報', 'Upcoming Event'],
    ['.whatsSolaBody', `令和元年度より、文部科学省は、Society5.0時代に向けて、イノベーティブなグローバル人材を育成するため、高等学校と国内外の大学，企業，国際機関等が協働し、高校生国際会議の開催等、高校生へ高度な学びを提供するネットワークの形成を目指すＷＷＬ（ワールド・ワイド・ラーニング）コンソーシアム構築事業を実施しています。<br><br>本学園が、文部科学省より、その拠点校に指定されてから、３年目を迎えました。最終年度にあたる本年、そのまとめとして、学びのオリンピック「SOLA 2021」（Shibuya Olympiad in Liberal Arts 2021）を開催することとなりました。テーマを「SDGs～私たちのつくる未来～」とし、模擬国際界、コンペティション、プレゼンテーションなど、様々な種目（部門）で中高生が互いに学び合い、気づきを得る一日になることを期待しております。このような中高生による中高生のための国際大会は世界にも類を見ない記念すべき試みです。皆様のご参加をお待ちしております。​<br> ​<br> ​<br>WWLコンソーシアム構築支援事業研究開発報告書をご覧ください：<br><br><a class="links" target="_blank" href="https://www.shibushibu.jp/wp-content/uploads/2021/04/2020wwl_kenkyukaihatsuhokokusho.pdf">https://www.shibushibu.jp/wp-content/uploads/2021/04/2020wwl_kenkyukaihatsuhokokusho.pdf</a>`, `Since 2019, the Ministry of Education, Culture, Sports, Science and Technology of Japan (MEXT), as a means of providing high school students with high quality learning and cultivating innovative people in preparation for Society 5.0, has been organizing the Worldwide Learning Consortium Project with the support of international organizations and high schools, universities and corporations across the globe.<br><br>It has been three years since our school was designated by MEXT as one of its hub schools. This year being the final year, we have decided to hold the Shibuya Olympiad in Liberal Arts 2021 as a summary of the program. This is a student-organized international exchange program consisting of several events, such as competitions, workshops, and presentations. The theme is "SDGs and the future we build." An international event of this scale run by and for high school students is yet to be seen and a commemorative event unlike any other in the world. <br><br>See the World Wide Learning Consortium Project Report: <br><br><a class="links" target="_blank" href="https://www.shibushibu.jp/wp-content/uploads/2021/04/2020wwl_kenkyukaihatsuhokokusho.pdf">https://www.shibushibu.jp/wp-content/uploads/2021/04/2020wwl_kenkyukaihatsuhokokusho.pdf</a>`],
    ['.slogan_text', 'スローガン', 'SLOGAN'],
    ['.slogan_body_text', ' SDGs達成のカギであるLiberal Artsの祭典を開催することによって、空のように世界をつなげ、可能性を無限に広げていこう！', "By celebrating and encouraging the liberal arts, a key aspect of our journey to achieve the SDGs, let's unite people under a single sky and explore infinite possibilities together!"],
    ['.principal_text', '​校長先生より一言', 'Message from Our Principal'],
    ['.principal_body_text', `　ようこそ、SOLA2022（Shibuya Olympiad in Liberal Arts 2022）へ。昨年のSOLA2021に引き続き、今夏もSOLA2022を開催できることをとても喜ばしく思います。SOLAは、渋谷教育学園渋谷中学高等学校が中心となって運営する、中高校生の中高校生による中高校生のための大会です。国内外の中高生が一同に集い、SDGs解決のカギとなるLiberal Artsの力を競い、披露し、未来に向けたメッセージを発信する場です。<br>　COVID-19の影響は、私たちの学校生活への大きな影響を与えましたが、学びは個人で為すだけのものではなく、互いにつながりあうことが大切だと気づかされました。未来に向けて、人々が自立しながらも共同体として支え合う新しい社会が求められています。対面とオンラインは、対立する２つのツールではなく、互いに補完しあい、よりよい未来をつくるための重要なツールです。若い英知を結集し、テーマ「SDGs～私たちのつくる未来～」にふさわしい一日になることを期待しています。<br>　最後になりましたが、この大会を開催するにあたり、ご支援ご協力いただきました多くの企業、大学、団体の皆様に心より御礼申し上げます。`, `Welcome to SOLA2022 (Shibuya Olympiad in Liberal Arts 2022). Following last year's SOLA2021, we are very pleased to host SOLA2022 this summer, a competition for middle and high school students by middle and high school students, organized primarily by Shibuya Kyoiku Gakuen Shibuya Junior and Senior High School. It is a place where junior high and high school students from Japan and abroad come together to compete and showcase their Liberal Arts skills, which are the key to solving the SDGs, and to send a message for the future.<br>The impact of COVID-19 on our school life has been profound, and it has made us realize that learning is not something we can do individually, but that it is important to connect with each other. As we look toward the future, we need a new society where people are independent, yet support each other as a community. Face-to-face and online are not two opposing tools, but important tools that complement each other to create a better future. I hope that this conference will be a day that brings together young wisdom and is worthy of the theme "SDGs: The Future We Create.<br>　Finally, I would like to express my sincere gratitude to the many companies, universities, and organizations that have supported and cooperated with us in organizing this conference.`],
    ['.fromPrincipal', '渋谷教育学園渋谷中学高等学校<br>校長　高際 伊都子', 'Itsuko Takagiwa<br><br>Principal　Shibuya Kyoiku Gakuen<br>Shibuya Junior & Senior High School '],
];

$(window).on('load', function() {
    for (let i = 0; i < translateText.length; i++) {
        if (location.href.indexOf('lang=jp') >= 0) {
            $(translateText[i][0]).html(translateText[i][1]);
        } else {
            $(translateText[i][0]).html(translateText[i][2]);
        }
    }
});